from polymatgen.core.polymer import Polymer


def write_lammps_summary(polymer: Polymer, filepath: str) -> None:
    """
    Write a human-readable LAMMPS-style summary file for a polymer system.
    This is a lightweight summary, not a full LAMMPS data file.
    Full atomistic LAMMPS files require 3D coordinates (coming in Phase 4).
    """
    lines = []
    lines.append(f"# LAMMPS summary for {polymer.name or 'unnamed polymer'}")
    lines.append("# Generated by polymatgen")
    lines.append("")
    lines.append(f"# Number of chains: {len(polymer.chains)}")
    lines.append(f"# Mn: {polymer.Mn:.2f} g/mol")
    lines.append(f"# Mw: {polymer.Mw:.2f} g/mol")
    lines.append(f"# Dispersity: {polymer.dispersity:.4f}")
    lines.append("")
    lines.append("# Chain distribution:")
    lines.append("# index  DP  Mw(chain)  tacticity  monomers")

    for i, chain in enumerate(polymer.chains):
        monomer_names = ",".join(m.name for m in chain.monomers)
        lines.append(
            f"  {i+1:<6} {chain.degree_of_polymerization:<5} "
            f"{chain.molecular_weight:<12.2f} {chain.tacticity:<12} {monomer_names}"
        )

    with open(filepath, "w") as f:
        f.write("\n".join(lines))
    print(f"LAMMPS summary written to {filepath}")


def read_lammps_summary(filepath: str) -> dict:
    """
    Read back the key statistics from a polymatgen LAMMPS summary file.
    Returns a dict with Mn, Mw, dispersity, and chain count.
    """
    stats = {}
    with open(filepath, "r") as f:
        for line in f:
            if "Number of chains" in line:
                stats["n_chains"] = int(line.split(":")[-1].strip())
            elif "Mn:" in line:
                stats["Mn"] = float(line.split(":")[-1].strip().split()[0])
            elif "Mw:" in line:
                stats["Mw"] = float(line.split(":")[-1].strip().split()[0])
            elif "Dispersity:" in line:
                stats["dispersity"] = float(line.split(":")[-1].strip())
    return stats
